    {
        "model": {
            "finalPrice": 0,
            "serviceFee": 0,
            "reservations": [
                {
                    "inventoryId": "456f2e81-4d76-43c4-943d-a42e08157c8c",
                    "pricePerItem": 0,
                    "currencyCode": None,
                    "vat": 0,
                    "notes": None,
                    "reservationDateCreated": "2022-09-24T13:38:33Z",
                    "notesInstructions": "",
                    "requiredInventoryIdReservations": [],
                    "availability": 80,
                    "reservedQuantity": 1,
                    "isProductVariantActive": True,
                    "isProductVariantMarkedAsOutOfStock": False,
                    "isProductVariantTransferable": True,
                    "isProductVariantHakaAuthenticationRequired": False,
                    "productVariantMaximumItemQuantityPerUser": 1,
                    "productVariantMaximumReservableQuantity": 1,
                    "productVariantMinimumReservableQuantity": 1,
                    "productVariantIsCountedTowardsMinTotalProductReservationsPerCheckout": False,
                    "variantId": "111bf81d-86f3-4357-b68e-4ca47bd26d17",
                    "variantName": "Tampere Challenge - Group 22",
                    "variantMediaFilename": None,
                    "linkedProductVariants": [],
                    "accessControlMemberships": [],
                    "contentsMemberships": [],
                    "productId": "e2c650b0-27f0-4629-a800-ab6959a527ad",
                    "productType": 1,
                    "productName": "Tampere Challenge",
                    "productMediaFilename": "xl_7eb94661b7782171cccbe040eea1fed952ba460690712e9c80592d9a.jpeg",
                    "productDateSalesFrom": "2022-09-19T23:55:00+03:00",
                    "minTotalReservationsPerCheckout": None,
                    "companyId": "916c9926-7548-4dcb-9295-e698645c2b03",
                    "companyName": "ESN FINT",
                }
            ],
            "currencyCode": None,
            "reservationsCount": 1,
            "reservationsTimeLeft": 1449,
        },
        "links": None,
    },
    {
        "model": {
            "finalPrice": 0,
            "serviceFee": 0,
            "reservations": [
                {
                    "inventoryId": "456f2e81-4d76-43c4-943d-a42e08157c8c",
                    "pricePerItem": 0,
                    "currencyCode": None,
                    "vat": 0,
                    "notes": None,
                    "reservationDateCreated": "2022-09-24T13:38:33Z",
                    "notesInstructions": "",
                    "requiredInventoryIdReservations": [],
                    "availability": 80,
                    "reservedQuantity": 1,
                    "isProductVariantActive": True,
                    "isProductVariantMarkedAsOutOfStock": False,
                    "isProductVariantTransferable": True,
                    "isProductVariantHakaAuthenticationRequired": False,
                    "productVariantMaximumItemQuantityPerUser": 1,
                    "productVariantMaximumReservableQuantity": 1,
                    "productVariantMinimumReservableQuantity": 1,
                    "productVariantIsCountedTowardsMinTotalProductReservationsPerCheckout": False,
                    "variantId": "111bf81d-86f3-4357-b68e-4ca47bd26d17",
                    "variantName": "Tampere Challenge - Group 22",
                    "variantMediaFilename": None,
                    "linkedProductVariants": [],
                    "accessControlMemberships": [],
                    "contentsMemberships": [],
                    "productId": "e2c650b0-27f0-4629-a800-ab6959a527ad",
                    "productType": 1,
                    "productName": "Tampere Challenge",
                    "productMediaFilename": "xl_7eb94661b7782171cccbe040eea1fed952ba460690712e9c80592d9a.jpeg",
                    "productDateSalesFrom": "2022-09-19T23:55:00+03:00",
                    "minTotalReservationsPerCheckout": None,
                    "companyId": "916c9926-7548-4dcb-9295-e698645c2b03",
                    "companyName": "ESN FINT",
                }
            ],
            "currencyCode": None,
            "reservationsCount": 1,
            "reservationsTimeLeft": 1449,
        },
        "links": None,
    },
    {
        "model": {
            "finalPrice": 0,
            "serviceFee": 0,
            "reservations": [
                {
                    "inventoryId": "456f2e81-4d76-43c4-943d-a42e08157c8c",
                    "pricePerItem": 0,
                    "currencyCode": None,
                    "vat": 0,
                    "notes": None,
                    "reservationDateCreated": "2022-09-24T13:38:33Z",
                    "notesInstructions": "",
                    "requiredInventoryIdReservations": [],
                    "availability": 80,
                    "reservedQuantity": 1,
                    "isProductVariantActive": True,
                    "isProductVariantMarkedAsOutOfStock": False,
                    "isProductVariantTransferable": True,
                    "isProductVariantHakaAuthenticationRequired": False,
                    "productVariantMaximumItemQuantityPerUser": 1,
                    "productVariantMaximumReservableQuantity": 1,
                    "productVariantMinimumReservableQuantity": 1,
                    "productVariantIsCountedTowardsMinTotalProductReservationsPerCheckout": False,
                    "variantId": "111bf81d-86f3-4357-b68e-4ca47bd26d17",
                    "variantName": "Tampere Challenge - Group 22",
                    "variantMediaFilename": None,
                    "linkedProductVariants": [],
                    "accessControlMemberships": [],
                    "contentsMemberships": [],
                    "productId": "e2c650b0-27f0-4629-a800-ab6959a527ad",
                    "productType": 1,
                    "productName": "Tampere Challenge",
                    "productMediaFilename": "xl_7eb94661b7782171cccbe040eea1fed952ba460690712e9c80592d9a.jpeg",
                    "productDateSalesFrom": "2022-09-19T23:55:00+03:00",
                    "minTotalReservationsPerCheckout": None,
                    "companyId": "916c9926-7548-4dcb-9295-e698645c2b03",
                    "companyName": "ESN FINT",
                }
            ],
            "currencyCode": None,
            "reservationsCount": 1,
            "reservationsTimeLeft": 1449,
        },
        "links": None,
    },
]
